---
abstract: 'Install the Curses::UI modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Curses-UI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Curses::UI: 0.9609
  Curses::UI::DelimitedTextViewer: 0.1
  Curses::UI::Grid: 0.15
  Curses::UI::Mousehandler::GPM: 0.01
  Curses::UI::Number: 0.06
  Curses::UI::POE: 0.04
  Curses::UI::Time: 0.05
  Curses::UI::Volume: 0.01
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Curses-UI
  homepage: https://github.com/tupinek/Task-Curses-UI
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-Curses-UI
version: '0.03'
